import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";

import { Providers } from "./providers";
import { GlobalContextProvider } from "@/context/GlobalContext";
import ReduxProvider from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <ReduxProvider>
            <Providers>{props.children}</Providers>
          </ReduxProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
